[licenses]
allow = [
  "Apache-2.0",
  "MIT",
  "Unicode-3.0",
]

[licenses.private]
ignore = true

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
