[package]
name = "loftd-guest-init"
version.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "loftd-guest-init"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
libc.workspace = true
loftd-attach-protocol.workspace = true
vt100.workspace = true

[dev-dependencies]
tempfile.workspace = true
