[package]
name = "cang-guest-init"
version.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "cang-guest-init"
path = "src/main.rs"

[[bin]]
name = "cang-granted"
path = "src/bin/cang-granted.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
libc.workspace = true
cang-attach-protocol.workspace = true
cang-exec-protocol.workspace = true
vt100.workspace = true

[dev-dependencies]
tempfile.workspace = true
