use super::*;
use std::fs;
use std::process::Command;

#[test]
fn task_hostname_uses_current_directory_name() {
    assert_eq!(
        derive_task_hostname(std::path::Path::new("/tmp/project")),
        "project-agentbox"
    );
}

#[test]
fn task_hostname_sanitizes_current_directory_name() {
    assert_eq!(
        derive_task_hostname(std::path::Path::new("/tmp/My repo.name!")),
        "my-repo-name-agentbox"
    );
}

#[test]
fn task_hostname_falls_back_when_directory_name_has_no_slug_chars() {
    assert_eq!(
        derive_task_hostname(std::path::Path::new("/tmp/!!!")),
        "workspace-agentbox"
    );
}

#[test]
fn task_container_name_prefixes_unique_suffix_with_current_directory_name() {
    assert_eq!(
        derive_task_container_name_with_suffix(
            std::path::Path::new("/tmp/My repo.name!"),
            "random-suffix"
        ),
        "my-repo-name-random-suffix"
    );
}

#[test]
fn task_container_name_falls_back_when_directory_name_has_no_slug_chars() {
    assert_eq!(
        derive_task_container_name_with_suffix(std::path::Path::new("/tmp/!!!"), "random-suffix"),
        "workspace-random-suffix"
    );
}

const ENTRYPOINT: &str = include_str!("../nix/image/entrypoint.nix");

#[test]
fn libkrun_entrypoint_branch_is_env_gated_and_does_not_require_proxy_host() {
    let gate = r#"if [ "''${AGENTBOX_LIBKRUN_NIX_OVERLAY:-}" = "1" ]; then
    ensure_libkrun_passt_resolv_conf
    bootstrap_libkrun_nix_overlay
  fi"#;
    assert!(ENTRYPOINT.contains(gate));

    let libkrun_branch_start = ENTRYPOINT
        .find(r#"if [ "''${AGENTBOX_LIBKRUN_NIX_OVERLAY:-}" = "1" ]; then"#)
        .expect("libkrun branch should exist");
    let proxy_branch_start = ENTRYPOINT
        .find(r#"agentbox_proxy_host="''${AGENTBOX_NIX_PROXY_HOST:-}""#)
        .expect("legacy proxy branch should remain for non-libkrun drop mode");
    let libkrun_branch = &ENTRYPOINT[libkrun_branch_start..proxy_branch_start];

    assert!(libkrun_branch.contains("bootstrap_libkrun_nix_overlay"));
    assert!(libkrun_branch.contains("NIX_REMOTE#unix://"));
    assert!(!libkrun_branch.contains("AGENTBOX_NIX_PROXY_HOST"));
}

#[test]
fn libkrun_entrypoint_passt_dns_helper_is_passt_gated_and_runs_before_bootstrap() {
    let helper = entrypoint_passt_dns_helper();
    assert!(helper.contains("AGENTBOX_LIBKRUN_USE_PASST"));
    assert!(helper.contains("nameserver 169.254.1.1"));
    assert!(!helper.contains("AGENTBOX_LIBKRUN_NIX_OVERLAY"));

    let helper_call = ENTRYPOINT
        .find("\n    ensure_libkrun_passt_resolv_conf\n")
        .expect("passt DNS helper should be called in libkrun branch");
    let bootstrap_call = ENTRYPOINT
        .find("\n    bootstrap_libkrun_nix_overlay\n")
        .expect("libkrun bootstrap should be called in libkrun branch");
    assert!(
        helper_call < bootstrap_call,
        "passt DNS should be normalized before libkrun bootstrap"
    );
}

#[test]
fn libkrun_entrypoint_passt_dns_inserts_missing_nameserver_first() {
    assert_eq!(
        normalize_resolv_conf_with_entrypoint_helper(Some(
            "search example.test\nnameserver 8.8.8.8\noptions ndots:1\n"
        )),
        "nameserver 169.254.1.1\nsearch example.test\nnameserver 8.8.8.8\noptions ndots:1\n"
    );
}

#[test]
fn libkrun_entrypoint_passt_dns_keeps_existing_first_nameserver_without_duplicate() {
    let resolv_conf = "nameserver 169.254.1.1\nnameserver 8.8.8.8\n";
    assert_eq!(
        normalize_resolv_conf_with_entrypoint_helper(Some(resolv_conf)),
        resolv_conf
    );
}

#[test]
fn libkrun_entrypoint_passt_dns_moves_later_nameserver_to_first() {
    assert_eq!(
        normalize_resolv_conf_with_entrypoint_helper(Some(
            "nameserver 8.8.8.8\nnameserver 169.254.1.1\n"
        )),
        "nameserver 169.254.1.1\nnameserver 8.8.8.8\n"
    );
}

#[test]
fn libkrun_entrypoint_passt_dns_collapses_duplicate_nameservers() {
    assert_eq!(
        normalize_resolv_conf_with_entrypoint_helper(Some(
            "nameserver 169.254.1.1\nnameserver 8.8.8.8\nnameserver 169.254.1.1\n"
        )),
        "nameserver 169.254.1.1\nnameserver 8.8.8.8\n"
    );
}

#[test]
fn libkrun_entrypoint_passt_dns_preserves_resolver_context_after_passt_line() {
    assert_eq!(
        normalize_resolv_conf_with_entrypoint_helper(Some(
            "# generated by runtime\nsearch example.test\noptions timeout:1\nnameserver 1.1.1.1\n"
        )),
        "nameserver 169.254.1.1\n# generated by runtime\nsearch example.test\noptions timeout:1\nnameserver 1.1.1.1\n"
    );
}

#[test]
fn libkrun_entrypoint_passt_dns_creates_missing_resolv_conf() {
    assert_eq!(
        normalize_resolv_conf_with_entrypoint_helper(None),
        "nameserver 169.254.1.1\n"
    );
}

#[test]
fn libkrun_entrypoint_passt_dns_helper_is_noop_without_passt_env() {
    assert_eq!(
        run_resolv_conf_helper(Some("nameserver 8.8.8.8\n"), false),
        Some("nameserver 8.8.8.8\n".to_owned())
    );
}

#[test]
fn libkrun_entrypoint_preserves_lowerdir_mounts_overlay_and_starts_guest_daemon() {
    for required in [
        "mount --bind /nix \"$agentbox_lower_dir\"",
        "mount -o remount,bind,ro \"$agentbox_lower_dir\"",
        "btrfs filesystem resize max \"$agentbox_disk_mount\"",
        "mkdir -p \"$agentbox_upper_dir\" \"$agentbox_work_dir\" \"$agentbox_upper_dir/store\" \"$agentbox_upper_dir/var\"",
        "${pkgs.coreutils}/bin/cp -a --no-clobber \"$agentbox_lower_dir/var/.\" \"$agentbox_upper_dir/var/\"",
        "failed to preseed libkrun upperdir /nix/var from image lowerdir",
        "mkdir -p \"$agentbox_upper_dir/var/nix\"",
        "${pkgs.coreutils}/bin/chown :nixbld \"$agentbox_upper_dir/store\"",
        "chmod 1775 \"$agentbox_upper_dir/store\"",
        "chmod 0755 \"$agentbox_upper_dir/var\" \"$agentbox_upper_dir/var/nix\"",
        "lowerdir=$agentbox_lower_dir,upperdir=$agentbox_upper_dir,workdir=$agentbox_work_dir",
        "${pkgs.nix}/bin/nix-daemon &",
        "export NIX_REMOTE=\"unix://$agentbox_socket\"",
        "libkrun in-guest nix-daemon socket is not accessible after dropping privileges",
    ] {
        assert!(ENTRYPOINT.contains(required), "missing {required}");
    }
}

#[test]
fn libkrun_entrypoint_preseeds_store_and_var_nix_before_overlay_mount() {
    let resize = ENTRYPOINT
        .find("btrfs filesystem resize max \"$agentbox_disk_mount\"")
        .expect("btrfs resize should happen before upperdir preseed");
    let preseed_mkdir = ENTRYPOINT
        .find("mkdir -p \"$agentbox_upper_dir\" \"$agentbox_work_dir\" \"$agentbox_upper_dir/store\" \"$agentbox_upper_dir/var\"")
        .expect("upperdir /store and /var preseed mkdir should exist");
    let var_copy = ENTRYPOINT
        .find("${pkgs.coreutils}/bin/cp -a --no-clobber \"$agentbox_lower_dir/var/.\" \"$agentbox_upper_dir/var/\"")
        .expect("image /nix/var should be copied into upperdir before overlay mount");
    let var_nix_mkdir = ENTRYPOINT
        .find("mkdir -p \"$agentbox_upper_dir/var/nix\"")
        .expect("upperdir /var/nix preseed mkdir should exist");
    let preseed_chmod = ENTRYPOINT
        .find("chmod 1775 \"$agentbox_upper_dir/store\"")
        .expect("upperdir /store chmod should exist");
    let var_nix_chmod = ENTRYPOINT
        .find("chmod 0755 \"$agentbox_upper_dir/var\" \"$agentbox_upper_dir/var/nix\"")
        .expect("upperdir /var/nix preseed chmod should exist");
    let preseed_chown = ENTRYPOINT
        .find("${pkgs.coreutils}/bin/chown :nixbld \"$agentbox_upper_dir/store\"")
        .expect("upperdir /store group ownership should be set to nixbld");
    let overlay_mount = ENTRYPOINT
        .find("${pkgs.util-linux}/bin/mount -t overlay overlay")
        .expect("overlay mount should exist");
    let socket_mkdir = ENTRYPOINT
        .find("mkdir -p /nix/var/nix/daemon-socket")
        .expect("daemon socket directory mkdir should exist");
    let daemon_start = ENTRYPOINT
        .find("${pkgs.nix}/bin/nix-daemon &")
        .expect("nix-daemon start should exist");

    assert!(
        resize < preseed_mkdir,
        "btrfs resize should happen before upperdir /var/nix preseed"
    );
    assert!(
        preseed_mkdir < preseed_chmod,
        "upperdir /var mkdir should happen before chmod"
    );
    assert!(
        preseed_mkdir < var_copy,
        "upperdir /var should exist before copying image /nix/var"
    );
    assert!(
        var_copy < var_nix_mkdir,
        "image /nix/var copy should happen before ensuring upperdir /var/nix exists"
    );
    assert!(
        var_nix_mkdir < preseed_chmod,
        "upperdir /var/nix mkdir should happen before chmod"
    );
    assert!(
        preseed_chown < preseed_chmod,
        "upperdir /store group ownership should be set before final chmod"
    );
    assert!(
        preseed_chown < overlay_mount,
        "upperdir /store group ownership should be set before overlay mount"
    );
    assert!(
        preseed_chmod < overlay_mount,
        "upperdir /store chmod should happen before overlay mount"
    );
    assert!(
        var_nix_chmod < overlay_mount,
        "upperdir /var/nix chmod should happen before overlay mount"
    );
    assert!(
        var_copy < overlay_mount,
        "image /nix/var copy should happen before overlay mount"
    );
    assert!(
        overlay_mount < socket_mkdir,
        "daemon socket directory should be created after overlay mount"
    );
    assert!(
        socket_mkdir < daemon_start,
        "daemon socket directory should be created before nix-daemon starts"
    );
    assert!(
        !ENTRYPOINT.contains("chown -R :nixbld"),
        "libkrun bootstrap must not recursively chown /nix/store children"
    );
}

#[test]
fn libkrun_entrypoint_has_fail_fast_diagnostics_for_expected_failures() {
    for diagnostic in [
        "required tool '$tool_name' is not available",
        "libkrun /nix btrfs disk not found",
        "failed to preserve image /nix lowerdir",
        "failed to mount libkrun /nix btrfs disk",
        "failed to mount libkrun overlay at /nix",
        "nix-daemon exited before creating",
        "nix-daemon did not create",
    ] {
        assert!(ENTRYPOINT.contains(diagnostic), "missing {diagnostic}");
    }
}

#[test]
fn image_includes_btrfs_progs_for_guest_bootstrap() {
    let layers = include_str!("../nix/image/layers.nix");
    assert!(layers.contains("pkgs.btrfs-progs"));
}

fn entrypoint_passt_dns_helper() -> String {
    let start = ENTRYPOINT
        .find("# BEGIN agentbox passt DNS helper")
        .expect("passt DNS helper start marker should exist");
    let end = ENTRYPOINT
        .find("# END agentbox passt DNS helper")
        .expect("passt DNS helper end marker should exist");
    ENTRYPOINT[start..end].replace("''${", "${")
}

fn normalize_resolv_conf_with_entrypoint_helper(input: Option<&str>) -> String {
    run_resolv_conf_helper(input, true).expect("resolv.conf should exist after passt normalization")
}

fn run_resolv_conf_helper(input: Option<&str>, passt_enabled: bool) -> Option<String> {
    let test_dir = std::env::temp_dir().join(format!(
        "agentbox-resolv-test-{}-{}",
        std::process::id(),
        unique_test_suffix()
    ));
    fs::create_dir_all(&test_dir).expect("test temp dir should be created");

    let resolv_conf = test_dir.join("resolv.conf");
    if let Some(contents) = input {
        fs::write(&resolv_conf, contents).expect("input resolv.conf should be written");
    }

    let env_line = if passt_enabled {
        "export AGENTBOX_LIBKRUN_USE_PASST=1"
    } else {
        "unset AGENTBOX_LIBKRUN_USE_PASST"
    };
    let script = format!(
        r#"set -euo pipefail
tmpdir="{tmpdir}"
{helper}
{env_line}
ensure_libkrun_passt_resolv_conf "{resolv_conf}"
"#,
        tmpdir = test_dir.display(),
        helper = entrypoint_passt_dns_helper(),
        env_line = env_line,
        resolv_conf = resolv_conf.display(),
    );

    let output = Command::new("bash")
        .arg("-c")
        .arg(script)
        .output()
        .expect("bash should run entrypoint helper fixture");
    assert!(
        output.status.success(),
        "entrypoint helper fixture failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let result = fs::read_to_string(&resolv_conf).ok();
    fs::remove_dir_all(&test_dir).expect("test temp dir should be removed");
    result
}

fn unique_test_suffix() -> String {
    use std::sync::atomic::{AtomicUsize, Ordering};

    static COUNTER: AtomicUsize = AtomicUsize::new(0);
    COUNTER.fetch_add(1, Ordering::Relaxed).to_string()
}
